# Generated by Django 3.0 on 2021-12-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='label',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='推論結果'),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='proba',
            field=models.FloatField(default=0.0, verbose_name='信頼度'),
        ),
    ]
